// <auto-generated />
namespace CursoWebApi.Projeto2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class criarBanco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(criarBanco));
        
        string IMigrationMetadata.Id
        {
            get { return "202001041841415_criar Banco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
